### MEAL ENDPOINTS

### Create meal
POST http://localhost:8080/meals
Content-Type: application/json

{
  "userId": "(Long) userId",
  "dateTime": "(ISO-8601) DateTime"
}

### Delete meal

DELETE http://localhost:8080/meals/{mealId}

### get meal summary
GET http://localhost:8080/meals/{mealId}/summary


### MEALFOOD ENDPOINTS

### Add food to meal
POST http://localhost:8080/meals/{mealId}/foods
Content-Type: application/json

{
  "foodName": "foodName",
  "quantity": "(Double) quantity",
  "unit": "g"
}

### Update mealFood Quantity

PATCH http://localhost:8080/meals/{mealId}/foods/{mealFoodId}
Content-Type: application/json

{
  "quantity": "(double) quantity"
}

### Delete MealFood From Meal
DELETE http://localhost:8080/meals/{mealId}/foods/{mealFoodId}


### USER ENDPOINTS

### Create User
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "NomeTeste",
  "email": "email@teste.com"
}

### Get user by Id
GET http://localhost:8080/users/{userId}

### Get all users (Only in Dev)
GET http://localhost:8080/users

### get User daily summary
GET http://localhost:8080/users/{userId}/daily-summary?date=YYYY-MM-DD

### List User Meals by date
GET http://localhost:8080/users/{userId}/meals?date=YYYY-MM-DD

